"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { Trend, LaunchPackage, AgentLogEntry } from "@/lib/types";
import { useWallet } from "@/hooks/useWallet";
import TrendFeed from "@/components/TrendFeed";
import LaunchPackageView from "@/components/LaunchPackage";
import WalletButton from "@/components/WalletButton";

let logCounter = 0;
function makeLog(type: AgentLogEntry["type"], message: string): AgentLogEntry {
  return { id: String(logCounter++), timestamp: Date.now(), type, message };
}

export default function Home() {
  const wallet = useWallet();
  const [trends, setTrends] = useState<Trend[]>([]);
  const [selectedTrend, setSelectedTrend] = useState<Trend | null>(null);
  const [agentLog, setAgentLog] = useState<AgentLogEntry[]>([]);
  const [isLoadingTrends, setIsLoadingTrends] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [streamingText, setStreamingText] = useState("");
  const [pkg, setPkg] = useState<LaunchPackage | null>(null);
  const [packagesGenerated, setPackagesGenerated] = useState(0);
  const hasAutoGenerated = useRef(false);

  const addLog = useCallback((entry: Omit<AgentLogEntry, "id" | "timestamp">) => {
    setAgentLog((prev) => [...prev.slice(-50), makeLog(entry.type, entry.message)]);
  }, []);

  const handleGenerate = useCallback(
    async (trend: Trend) => {
      if (isGenerating) return;
      setSelectedTrend(trend);
      setIsGenerating(true);
      setStreamingText("");
      setPkg(null);

      addLog({ type: "thinking", message: `Analyzing: "${trend.title.slice(0, 50)}..."` });
      addLog({ type: "scan", message: "Computing cultural context and virality vectors..." });

      try {
        const response = await fetch("/api/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ trend }),
        });

        if (!response.body) throw new Error("No response stream");

        const reader = response.body.getReader();
        const decoder = new TextDecoder();
        let fullText = "";
        let buffer = "";

        addLog({ type: "thinking", message: "Generating launch package..." });

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split("\n");
          buffer = lines.pop() ?? "";

          for (const line of lines) {
            if (!line.startsWith("data: ")) continue;
            const raw = line.slice(6).trim();

            if (raw === "[DONE]") {
              try {
                const parsed: LaunchPackage = JSON.parse(fullText);
                const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(
                  parsed.imagePrompt + ", cute cartoon mascot, vibrant colors, no text"
                )}?width=512&height=512&nologo=true&seed=${Date.now() % 10000}`;
                setPkg({ ...parsed, imageUrl });
                setPackagesGenerated((n) => n + 1);
                addLog({ type: "success", message: `Package ready: $${parsed.ticker} — ${parsed.coinName}` });
                addLog({ type: "success", message: `Virality score: ${parsed.viralityScore}/100` });
              } catch {
                addLog({ type: "error", message: "Failed to parse response. Check your GOOGLE_API_KEY." });
              }
              break;
            }

            try {
              const { text, error } = JSON.parse(raw);
              if (error) { addLog({ type: "error", message: error }); break; }
              if (text) { fullText += text; setStreamingText(fullText); }
            } catch { /* ignore */ }
          }
        }
      } catch (err) {
        addLog({ type: "error", message: err instanceof Error ? err.message : "Generation failed" });
      } finally {
        setIsGenerating(false);
      }
    },
    [isGenerating, addLog]
  );

  const handleRegenerate = useCallback(() => {
    if (selectedTrend) handleGenerate(selectedTrend);
  }, [selectedTrend, handleGenerate]);

  useEffect(() => {
    const boot = async () => {
      addLog({ type: "scan", message: "MemeOS autonomous agent initializing..." });
      addLog({ type: "info", message: "Connecting to trend intelligence network..." });
      try {
        const res = await fetch("/api/trends");
        const data = await res.json();
        setTrends(data.trends ?? []);
        addLog({ type: "success", message: `Loaded ${data.trends?.length ?? 0} trending signals` });
        setTimeout(() => addLog({ type: "scan", message: "Scanning Reddit, CoinGecko, Crypto Twitter..." }), 800);
        setTimeout(() => addLog({ type: "thinking", message: "Scoring virality vectors for all signals..." }), 2000);
        setTimeout(() => addLog({ type: "info", message: "Top opportunity identified. Auto-generating in 4s..." }), 3000);
      } catch {
        addLog({ type: "error", message: "Failed to fetch trends. Using fallback data." });
      } finally {
        setIsLoadingTrends(false);
      }
    };
    boot();
  }, [addLog]);

  useEffect(() => {
    if (trends.length > 0 && !hasAutoGenerated.current && !isGenerating && !selectedTrend) {
      hasAutoGenerated.current = true;
      const timer = setTimeout(() => {
        addLog({ type: "scan", message: `Auto-selecting top signal: "${trends[0].title.slice(0, 45)}..."` });
        handleGenerate(trends[0]);
      }, 4000);
      return () => clearTimeout(timer);
    }
  }, [trends, isGenerating, selectedTrend, handleGenerate, addLog]);

  return (
    <div className="grid-bg min-h-screen flex flex-col">
      {/* Header */}
      <header
        className="flex items-center justify-between px-6 py-3 border-b"
        style={{ borderColor: "var(--border)", background: "rgba(7,7,26,0.95)", backdropFilter: "blur(10px)", position: "sticky", top: 0, zIndex: 10 }}
      >
        <div className="flex items-center gap-4">
          <span className="text-xl font-bold shimmer-text tracking-tight">MemeOS</span>
          <div className="hidden sm:flex items-center gap-3 text-xs" style={{ color: "var(--text-muted)" }}>
            <span style={{ color: "var(--border-bright)" }}>|</span>
            <span>{trends.length} signals</span>
            <span style={{ color: "var(--border-bright)" }}>|</span>
            <span>{packagesGenerated} packages</span>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <div
              className="w-2 h-2 rounded-full pulse-dot"
              style={{ background: isGenerating ? "#9945ff" : "#00ff88", boxShadow: `0 0 6px ${isGenerating ? "#9945ff" : "#00ff88"}` }}
            />
            <span className="text-xs font-bold hidden sm:block" style={{ color: isGenerating ? "#9945ff" : "#00ff88" }}>
              {isGenerating ? "GENERATING" : "AGENT ACTIVE"}
            </span>
          </div>
          <WalletButton wallet={wallet} />
        </div>
      </header>

      {/* Main */}
      <main className="flex-1 flex overflow-hidden" style={{ height: "calc(100vh - 57px)" }}>
        {/* Left sidebar */}
        <div
          className="flex flex-col p-4 overflow-hidden"
          style={{ width: "340px", minWidth: "340px", borderRight: "1px solid var(--border)", background: "rgba(7,7,26,0.6)" }}
        >
          <TrendFeed
            trends={trends}
            selectedTrend={selectedTrend}
            onSelect={handleGenerate}
            agentLog={agentLog}
            isLoading={isLoadingTrends}
          />
        </div>

        {/* Right panel */}
        <div className="flex-1 p-6 overflow-y-auto">
          <LaunchPackageView
            selectedTrend={selectedTrend}
            streamingText={streamingText}
            isGenerating={isGenerating}
            pkg={pkg}
            wallet={wallet}
            onRegenerate={handleRegenerate}
          />
        </div>
      </main>
    </div>
  );
}
